run:
  concurrency: 4
  timeout: 30m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs: []
  skip-dirs-use-default: true
  skip-files: []
  modules-download-mode: readonly
  allow-parallel-runners: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  gocritic:
    enabled-tags:
      - performance
  gofumpt:
    lang-version: "1.18"
  gosimple:
    go: "1.18"
    checks: [ "all" ]
  govet:
    check-shadowing: true
    enable:
      - atomicalign
      - shadow
  misspell:
    locale: US
  staticcheck:
    go: "1.18"
    checks: [ "all" ]
  stylecheck:
    go: "1.18"
  unparam:
    check-exported: true
  unused:
    go: "1.18"
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.com/etke.cc/postmoogle)
    section-separators:
      - newLine
linters:
  disable-all: false
  enable:
    - megacheck
    - govet
    - errcheck
    - gci
    - gocognit
    - nestif
      # - gocritic # ref: https://github.com/golangci/golangci-lint/issues/2649#issue-1170906525
    - gofumpt
    - goimports
    - gosimple
    - govet
    - misspell
    - staticcheck
    - stylecheck
    - unparam
    - unused
  fast: false


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
