# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
      - -X main.version={{.Version}}
    flags:
      - -tags=timetzdata,goolm
    main: ./cmd/agru
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: agru
    homepage: "https://github.com/etkecc/agru"
    description: "Fast, drop-in ansible-galaxy replacement for updating role requirements"
    license: "AGPL-3.0-only"
    directory: Formula
    repository:
      owner: etkecc
      name: agru
      branch: main
    install: |
      bin.install "agru"
    test: |
      assert_match version.to_s, shell_output("#{bin}/agru -v")

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
