# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agru < Formula
  desc "Fast, drop-in ansible-galaxy replacement for updating role requirements"
  homepage "https://github.com/etkecc/agru"
  version "0.3.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etkecc/agru/releases/download/v0.3.0/agru_Darwin_x86_64.tar.gz"
      sha256 "34dd3647c093822462fdf21cc03820c1a72e06f7a9fc8c6a6ddef69aed048b2b"

      define_method(:install) do
        bin.install "agru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etkecc/agru/releases/download/v0.3.0/agru_Darwin_arm64.tar.gz"
      sha256 "780f24341eeadcf87adde41628828c78417b0059c32f053fa8ffe88bc4f60afa"

      define_method(:install) do
        bin.install "agru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/etkecc/agru/releases/download/v0.3.0/agru_Linux_x86_64.tar.gz"
      sha256 "1601916b0762d37c25ca2ba85428d44df02057bf4125b776a9258efabe33c015"
      define_method(:install) do
        bin.install "agru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etkecc/agru/releases/download/v0.3.0/agru_Linux_arm64.tar.gz"
      sha256 "1684f69eca589003d8302ccb50edb4235d52d01ecd50564e1cb6417c026b8d4a"
      define_method(:install) do
        bin.install "agru"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agru -v")
  end
end
